name = "cobble"
author = "ei-fie"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba096da7efd5902d34c22387d6baddc54911658708c3926f01f907623c481486"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
