name = "cobble"
author = "ei-fie"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9b8ce57041eff370287b14d7c9beeff6c40ce582f14f4a9ff68bb12ca90bec5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
