name = "cobble"
author = "ei-fie"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bd8b06f36cbc6c3b28fa8ae0478ee7f60a62f0b11a81af2e31800ccfc876464"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
